var friends = ["oly" , "koly", "doly"];
console.log(friends);
friends.push("poly")
console.log(friends);
friends.push("joly");
friends.push("moly");
friends.push("holy");
friends.push("roly");
console.log(friends);
friends.pop()
console.log(friends);
friends.pop();
console.log(friends)
friends.pop();
console.log(friends);
friends.pop()
friends.pop()
friends.pop();
console.log(friends)
friends.shift()
console.log(friends);
friends.shift()
friends.unshift("alu","khalu","milu")
console.log(friends);
friends.shift()
console.log(friends);
friends.shift();
console.log(friends)